name: 'Build and push a spack develop container'
description: 'Build and push a spack develop container to ghcr.io'
branding:
  icon: 'play'
  color: 'blue'
inputs:
  operating_system:
    description: 'Base operating system layer (available at https://github.com/orgs/spack/packages)'
    required: false
    default: 'ubuntu-jammy'
  spack_version:
    description: 'Spack version (e.g. v0.19.0)'
    required: false
    default: 'latest'
  registry:
    description: 'Container registry to push to (defaults to ghcr.io)'
    required: false
    default: 'ghcr.io'
  repo:
    description: 'Container repository to push to (defaults to username)'
    required: false
    default: ''
  name:
    description: 'Container image name to push (defaults to repository)'
    required: false
    default: ''
  tag:
    description: 'Container image tag to push (defaults to github.sha)'
    required: false
    default: ''
  environment:
    description: 'Environment yaml file'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
      - uses: spack/containerize
        with:
          os: ${{ inputs.os }}
          version: ${{ inputs.spack_version }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
        spack containerize | tee Dockerfile
      - uses: docker/build-push-action@v3
        with:
          path: .
          push: true
          tags: ${{ github.actor }}/${{ inputs.name }}:${{ inputs.tag || github.sha }}
